---
repos:

  # Top level stuff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # isort
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  # black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --line-length=120
          - --include='\.pyi?$\'

        # exclude the following folders from formatting
          - --exclude= ```
            /(
                \.git
              | \.__pycache__
              | \.hg
              | \.mypy_cache
              | \.pre-commit-config.yaml
              | \.proto
              | \.tox
              | \.venv
              | venv
              | _build
              | buck-out
              | build
              | dist
            )/
            ```

        language_version: python3.10

  # Flake 8
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - "--exclude=.git,__pycache__,.proto,*_pb2.py,*_pb2_grpc.py"
          - "--max-line-length=120"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

  # yamlint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
